Repository bounswe/bounswe2024group11, pull requests merged in 2024-12, with the labels that each got.

#694 feat(be): implemented profile views and serializers, added swagger do…
  backend/core/serializers/profile_serializer.py
  backend/core/urls.py
  backend/core/views/profile_views.py
Labels: app: be, pri: high

#769 feat(be): implement follow endpoint
  backend/core/fixtures/3_forum_questions.json
  backend/core/migrations/0016_follow.py
  backend/core/models.py
  backend/core/permissions.py
  backend/core/serializers/profile_serializer.py
  backend/core/serializers/serializers.py
  backend/core/urls.py
  backend/core/views/follow_views.py
  backend/core/views/profile_views.py
Labels: app: be, pri: high

#770 feat(be): semantically relate a forum question to other forum questions
  backend/core/serializers/forum_question_serializer.py
  backend/core/utils.py
  backend/core/views/forum_views.py
  backend/core/views/semantic_search_views.py
Labels: app: be, pri: high

#779 Forum question image upload
  backend/core/fixtures/3_forum_questions.json
  backend/core/migrations/0016_forumquestion_image_url.py
  backend/core/models.py
  backend/core/serializers/forum_question_serializer.py
  backend/core/serializers/serializers.py
  backend/core/views/forum_views.py
  client/pnpm-lock.yaml
  client/src/components/forum-card.tsx
  client/src/routes/Forum/Forum.data.tsx
  client/src/routes/Forum/Forum.schema.ts
  client/src/routes/Forum/NewForum.tsx
Labels: app: fe, app: be, pri: high

#777 feat(be): implement block endpoint
  backend/core/migrations/0017_block.py
  backend/core/models.py
  backend/core/permissions.py
  backend/core/serializers/profile_serializer.py
  backend/core/serializers/serializers.py
  backend/core/urls.py
  backend/core/views/block_views.py
Labels: app: be, pri: high

#781 feat(client): display realted forum questions
  client/src/routes/Forum/Forum.schema.ts
  client/src/routes/Forum/Question.tsx
Labels: app: fe, pri: high

#776 feat(be): implement CD endpoints for interest
  backend/core/urls.py
  backend/core/views/interest_views.py
Labels: app: be

#745 feat(mobile): add delete and edit button to forum questions
  mobile/App.tsx
  mobile/app/components/DeleteButton.tsx
  mobile/app/components/EditButton.tsx
  mobile/app/components/ForumQuestionCard.tsx
  mobile/app/screens/EditQuestion.tsx
  mobile/app/types/forum.ts
Labels: pri: medium, app:mobile

#746 feat(mobile): add UserCard and TabView to profile screen
  backend/core/views/jwt_views.py
  mobile/app/components/AuthorView.tsx
  mobile/app/components/ForumQuestionCard.tsx
  mobile/app/components/UserCard.tsx
  mobile/app/components/UserView.tsx
  mobile/app/screens/Profile.tsx
  mobile/app/types/quiz.ts
  mobile/app/types/user.ts
Labels: pri: medium, app:mobile

#783 feat(be): implement get endpoint for achievements
  backend/core/urls.py
  backend/core/views/achievement_views.py
Labels: app: be, pri: urgent

#782 feat(be): implement achievements notification
  backend/config/settings.py
  backend/core/achievements/__init__.py
  backend/core/achievements/conditions.py
  backend/core/achievements/services.py
  backend/core/middleware.py
  backend/core/serializers/achievement.py
  backend/core/serializers/profile_serializer.py
Labels: app: be, pri: high

#786 feat(client): voiceover context & component for pronunciation
  client/src/components/voiceover.tsx
  client/src/contexts/speechContext.tsx
  client/src/hooks/useSpeech.ts
  client/src/main.tsx
  client/src/routes/Quiz/Quiz.tsx
Labels: app: fe, pri: high

#800 fix(mobile): solve synchronization problems on Forum Questions Components for Mobile Application
  mobile/App.tsx
  mobile/app/components/DeleteButton.tsx
  mobile/app/components/ForumQuestionCard.tsx
  mobile/app/screens/Forum.tsx
  mobile/app/screens/ForumQuestionDetail.tsx
  mobile/app/screens/Profile.tsx
Labels: pri: medium, app:mobile

#807 feat(mobile): add delete and edit button to forum answers
  mobile/App.tsx
  mobile/app/components/DeleteAnswerButton.tsx
  mobile/app/components/EditAnswerButton.tsx
  mobile/app/components/ForumAnswerCard.tsx
  mobile/app/screens/EditAnswer.tsx
  mobile/app/screens/ForumQuestionDetail.tsx
  mobile/app/types/forum.ts
Labels: pri: medium, app:mobile

#805 feat(be): add proficiency to user model and profile serializer
  backend/core/migrations/0018_merge_0016_forumquestion_image_url_0017_block.py
  backend/core/migrations/0019_customuser_proficiency.py
  backend/core/models.py
  backend/core/serializers/profile_serializer.py
Labels: app: be, pri: medium

#793 feat(be): implement feed endpoint
  backend/core/urls.py
  backend/core/utils.py
  backend/core/views/feed_views.py
Labels: app: be, pri: high

#808 feat(be): implement leaderboard view and serializer
  backend/core/migrations/0019_customuser_score.py
  backend/core/models.py
  backend/core/serializers/leaderboard_serializer.py
  backend/core/urls.py
  backend/core/views/leaderboard_views.py
Labels: type: improvement, app: be, pri: high

#764 feat(client): multistep quiz creation
  backend/core/models.py
  client/package.json
  client/pnpm-lock.yaml
  client/src/api.ts
  client/src/components/button.tsx
  client/src/components/info-box.tsx
  client/src/components/input.tsx
  client/src/hooks/tagging.ts
  client/src/router.tsx
  client/src/routes/Forum/Forum.schema.ts
  client/src/routes/Forum/NewForum.tsx
  client/src/routes/Forum/NewForumHead.tsx
  client/src/routes/Quiz/NewQuiz/NewQuiz-utils.tsx
  client/src/routes/Quiz/NewQuiz/NewQuiz.data.tsx
  client/src/routes/Quiz/NewQuiz/NewQuiz.tsx
  client/src/routes/Quiz/NewQuiz/NewQuizDetails.tsx
  client/src/routes/Quiz/NewQuiz/NewQuizHead.tsx
  client/src/routes/Quiz/NewQuiz/NewQuizQuestion.tsx
  client/src/routes/Quiz/NewQuiz/NewQuizQuestionOptions.tsx
  client/src/routes/Quiz/NewQuiz/NewQuizQuestionOptionsHint.tsx
  client/src/routes/Quiz/NewQuiz/NewQuizQuestionOptionsHintCustom.tsx
  client/src/routes/Quiz/NewQuiz/WordSelectionView.tsx
  client/src/routes/Quiz/NewQuiz/state.ts
  client/src/routes/Quiz/Quiz.schema.ts
  client/src/routes/Quiz/Quiz.state.ts
  client/src/routes/Quiz/Quiz.tsx
  client/src/routes/Quiz/Quizzes.tsx
Labels: app: be, pri: high

#761 feat(client): show answers question by question on quizzes
  client/public/sfx/false.wav
  client/public/sfx/success.wav
  client/public/sfx/true.wav
  client/src/components/quiz-card.tsx
  client/src/contexts/SoundContext.tsx
  client/src/main.tsx
  client/src/router.tsx
  client/src/routes/Achievements/Achievements.tsx
  client/src/routes/Quiz/NewQuiz/NewQuizQuestionOptionsHint.tsx
  client/src/routes/Quiz/Quiz.Review.tsx
  client/src/routes/Quiz/Quiz.tsx
  client/src/routes/Quiz/QuizChoice.tsx
  client/src/utils.tsx
Labels: app: fe, pri: high

#817 feat(be) : implement filtering of blocked users in feed and quiz pages
  backend/core/views/feed_views.py
  backend/core/views/quiz_views.py
Labels: type: improvement, app: be, pri: high

#825 ux(client): `(cmd+K)` command menu to access navigation and actions
  client/src/components/command-button.tsx
  client/src/components/command-menu.tsx
  client/src/components/info-box.tsx
  client/src/components/tagselect.tsx
  client/src/contexts/CommandMenuContext.tsx
  client/src/contexts/SoundContext.tsx
  client/src/contexts/speechContext.tsx
  client/src/hooks/command-menu.ts
  client/src/hooks/pagination.ts
  client/src/hooks/useSpeech.ts
  client/src/main.tsx
  client/src/routes/Home/Home.main.tsx
  client/src/routes/Quiz/NewQuiz/NewQuizQuestionOptions.tsx
  client/src/routes/Quiz/NewQuiz/NewQuizQuestionOptionsHint.tsx
  client/src/routes/Quiz/NewQuiz/NewQuizQuestionOptionsHintCustom.tsx
  client/src/routes/Quiz/NewQuiz/WordSelectionView.tsx
  client/src/routes/Quiz/NewQuiz/state.ts
  client/src/routes/Quiz/QuizChoice.tsx
  client/src/routes/_root.tsx
Labels: type: improvement, app: fe, pri: low

#826 ux(client): display skeleton screens for route loadings
  client/src/index.css
  client/src/router.tsx
  client/src/routes/Achievements/Achievements.data.tsx
  client/src/routes/Achievements/Achievements.tsx
  client/src/routes/Achievements/Badge.tsx
  client/src/routes/Forum/Forum.data.tsx
  client/src/routes/Forum/Forum.tsx
  client/src/routes/Profile/Profile.data.tsx
  client/src/routes/Profile/Profile.tsx
  client/src/routes/Quiz/Quiz.End.tsx
  client/src/routes/Quiz/Quiz.Illustration.tsx
  client/src/routes/Quiz/Quiz.Start.tsx
  client/src/routes/Quiz/Quiz.data.tsx
  client/src/routes/Quiz/Quiz.tsx
  client/src/routes/Quiz/Quizzes.data.tsx
  client/src/routes/_loading.tsx
Labels: app: fe

#834 feat(client): implement clientside pagination for profile taken_quizzes and bookmarked_posts
  client/pnpm-lock.yaml
  client/src/components/bookmarked-forums.tsx
  client/src/components/quiz-card.tsx
  client/src/components/quizzes-taken.tsx
  client/src/routes/Forum/NewForum.tsx
  client/src/routes/Profile/Profile.tsx
  client/src/routes/Quiz/Quiz.Review.tsx
  client/src/routes/Quiz/Quizzes.tsx
  client/src/tests/string.test.ts
Labels: app: fe, pri: high

#849 fix(client): no longer reliance on the local storage for quiz answers
  backend/core/serializers/serializers.py
  client/src/components/forum-card.tsx
  client/src/components/navbar.tsx
  client/src/router.tsx
  client/src/routes/Achievements/Achievements.data.tsx
  client/src/routes/Forum/Forum.data.tsx
  client/src/routes/Leaderboard/Leaderboard.tsx
  client/src/routes/Profile/Profile.data.tsx
  client/src/routes/Quiz/Quiz.Review.tsx
  client/src/routes/Quiz/Quiz.data.tsx
  client/src/routes/Quiz/Quiz.schema.ts
  mobile/app/screens/Leaderboard.tsx
Labels: app: fe

#845 feat(client): semantic search for quizzes
  backend/core/migrations/0020_remove_quiz_quiz_point_ratequiz_comment.py
  client/src/components/command-menu.tsx
  client/src/components/quiz-card.tsx
  client/src/components/tag-search.tsx
  client/src/hooks/tagging.ts
  client/src/routes/Quiz/NewQuiz/NewQuizDetails.tsx
  client/src/routes/Quiz/NewQuiz/NewQuizQuestionOptions.tsx
  client/src/routes/Quiz/Quiz.data.tsx
  client/src/routes/Quiz/Quizzes.data.tsx
  client/src/routes/Quiz/Quizzes.tsx
Labels: app: fe, app: be

#863 feat(client): add semantic search to the forum
  client/src/components/blockings-modal.tsx
  client/src/routes/Forum/Forum.data.tsx
  client/src/routes/Forum/Forum.tsx
  client/src/routes/Leaderboard/Leaderboard.tsx
  client/src/routes/Profile/Profile.schema.ts
  client/src/routes/Profile/Profile.tsx
  client/src/routes/Quiz/Quizzes.tsx
  client/src/routes/_loading.tsx
Labels: app: fe, pri: high

#864 feat(be): implement sorting for forum page and quiz page
  backend/core/views/forum_views.py
  backend/core/views/quiz_views.py
Labels: app: be, pri: high

#866 feat(client): add proficiency selection to register
  backend/core/views/achievement_views.py
  client/src/components/navbar.tsx
  client/src/routes/Auth/Register.tsx
  client/src/routes/Forum/NewForum.tsx
  client/src/routes/Home/Home.data.tsx
  client/src/routes/Home/Home.tsx
  client/src/routes/_loading.tsx
Labels: app: fe, pri: high

#812 feat(be): implement classes for cron script to reset periodically in leaderboard
  backend/core/management/commands/__init__.py
  backend/core/management/commands/reset_leaderboard.py
  backend/core/tasks.py
Labels: type: improvement, app: be, pri: medium

#870 feat(client): add block unblock follow unfollow toast notification
  client/src/routes/Forum/NewForum.tsx
  client/src/routes/Forum/NewForumHead.tsx
  client/src/routes/Home/Home.EmptyInterest.tsx
  client/src/routes/Home/Home.tsx
  client/src/routes/Profile/Profile.data.tsx
  client/src/routes/Profile/Profile.tsx
  client/src/routes/Quiz/NewQuiz/NewQuiz.tsx
  client/src/routes/Quiz/NewQuiz/NewQuizHead.tsx
  client/src/routes/Quiz/NewQuiz/NewQuizQuestionOptions.tsx
  client/src/routes/Quiz/NewQuiz/NewQuizQuestionOptionsHint.tsx
Labels: app: fe, pri: high

#843 feat(mobile): implement follow feature
  mobile/App.tsx
  mobile/app/components/BookmarkButton.tsx
  mobile/app/components/DeleteAnswerButton.tsx
  mobile/app/components/DeleteButton.tsx
  mobile/app/components/FollowButton.tsx
  mobile/app/components/ForumQuestionCard.tsx
  mobile/app/components/NewQuizQuestion.tsx
  mobile/app/components/ProfileButton.tsx
  mobile/app/components/UserCard.tsx
  mobile/app/components/VoteAnswerButtonsView.tsx
  mobile/app/components/VoteButtonsView.tsx
  mobile/app/context/AuthContext.tsx
  mobile/app/screens/CreateQuestion.tsx
  mobile/app/screens/CreateQuiz.tsx
  mobile/app/screens/CreateQuizQuestion.tsx
  mobile/app/screens/EditAnswer.tsx
  mobile/app/screens/EditQuestion.tsx
  mobile/app/screens/Forum.tsx
  mobile/app/screens/ForumQuestionDetail.tsx
  mobile/app/screens/Profile.tsx
  mobile/app/screens/ProfileScreen.tsx
  mobile/app/screens/QuizFeed.tsx
  mobile/app/screens/ReviewCreateQuiz.tsx
  mobile/app/screens/ViewQuiz.tsx
  mobile/app/types/user.ts
  mobile/config.ts
Labels: pri: high, app:mobile

#872 feat(client): add and remove interests, suggested tags and people. feed layout improvements
  backend/core/views/feed_views.py
  client/src/components/avatar.tsx
  client/src/components/interest-tag.tsx
  client/src/components/tag-search.tsx
  client/src/components/user-card.tsx
  client/src/hooks/tagging.ts
  client/src/router.tsx
  client/src/routes/Auth/Register.tsx
  client/src/routes/Forum/Forum.data.tsx
  client/src/routes/Forum/Forum.tsx
  client/src/routes/Forum/Question.data.tsx
  client/src/routes/Home/Home.EmptyInterest.tsx
  client/src/routes/Home/Home.data.tsx
  client/src/routes/Home/Home.tsx
  client/src/routes/Home/HomeAddInterest.tsx
  client/src/routes/Home/HomeEmptySection.tsx
  client/src/routes/Home/HomeForum.tsx
  client/src/routes/Home/HomePeopleSuggestions.tsx
  client/src/routes/Home/HomeQuiz.tsx
  client/src/routes/Home/HomeTags.tsx
  client/src/routes/Profile/Profile.data.tsx
  client/src/routes/Profile/Profile.tsx
  client/src/routes/Quiz/NewQuiz/NewQuizQuestionOptions.tsx
  client/src/routes/Quiz/NewQuiz/WordSelectionView.tsx
  client/src/routes/_loading.tsx
  client/src/schemas.ts
Labels: app: fe, pri: high

#875 feat(client): display follower and following count on profile
  client/src/components/blockings-modal.tsx
  client/src/components/quiz-card.tsx
  client/src/components/tag-search.tsx
  client/src/components/user-card.tsx
  client/src/routes/Home/HomeAddInterest.tsx
  client/src/routes/Home/HomePeopleSuggestions.tsx
  client/src/routes/Profile/Profile.tsx
Labels: app: fe

#876 feat(client): update proficiency from user profile
  backend/core/views/feed_views.py
  client/src/router.tsx
  client/src/routes/Profile/ProficiencyChange.tsx
  client/src/routes/Profile/Profile.data.tsx
  client/src/routes/Profile/Profile.schema.ts
  client/src/routes/Profile/Profile.tsx
Labels: app: fe

#878 feat(client): indicate loading states on actions with photo upload
  client/pnpm-lock.yaml
  client/src/routes/Auth/Register.tsx
  client/src/routes/Forum/NewForum.tsx
Labels: app: fe, pri: high

#884 des(client): use distinct illustration for quiz and forum creation
  client/src/routes/Quiz/NewQuiz/NewQuizHead.tsx
Labels: type: improvement, app: fe, app: design

#885 feat(client): more concise forum question title while asking quiz que…
  client/src/routes/Quiz/Quiz.Review.tsx
Labels: app: fe, pri: high

#890 feat(mobile): add quiz result screen
  .vscode/settings.json
  backend/core/models.py
  backend/core/serializers/take_quiz_serializer.py
  mobile/App.tsx
  mobile/android/app/src/debug/AndroidManifest.xml
  mobile/app/components/QuizQuestion.tsx
  mobile/app/screens/QuizFeed.tsx
  mobile/app/screens/QuizResult.tsx
  mobile/app/screens/ReviewCreateQuiz.tsx
  mobile/app/screens/ViewQuiz.tsx
  mobile/app/types/quiz.ts
  mobile/config.ts
  mobile/ios/Podfile.lock
  mobile/package-lock.json
  mobile/package.json
  mobile/tsconfig.json
Labels: pri: high, app:mobile
