Repository bounswe/bounswe2024group11, pull requests merged in 2024-04, with the labels that each got.

#187 chore(web): bootstrap the repo structure
  frontend/.gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
  web/index.html
  web/package.json
  web/pnpm-lock.yaml
  web/src/App.tsx
  web/src/index.css
  web/src/theme.ts
Labels: app: fe, pri: medium

#189 feat(web): create example routes for csr
  web/src/App.tsx
Labels: app: fe, pri: medium

#197 fix: Fix a urlpattern in the config
  backend/config/urls.py
Labels: app: be, pri: medium

#219 feat: create endpoints for the user model
  backend/api/__init__.py
  backend/api/serializer.py
  backend/api/urls.py
  backend/api/views.py
  backend/config/settings.py
  backend/config/urls.py
  backend/user/__init__.py
  backend/user/admin.py
  backend/user/apps.py
  backend/user/migrations/0001_initial.py
  backend/user/migrations/__init__.py
  backend/user/models.py
  backend/user/tests.py
  backend/user/views.py
Labels: app: be, pri: medium

#221 Connect Backend to Hosted MySQL Server
  backend/.env.example
  backend/config/settings.py
  backend/requirements.txt
Labels: app: be, pri: medium

#226 fix(web): tailwindcss generates class names
  web/postcss.config.cjs
  web/tailwind.config.ts
Labels: type: bug, app: fe, pri: medium

#225 deps(web): use only npm as package manager
  web/package-lock.json
  web/package.json
  web/pnpm-lock.yaml
  web/yarn.lock
Labels: app: fe, pri: high, type: dependencies

#224 test(api): add unit tests for user model
  backend/api/tests/__init__.py
  backend/api/tests/test_setup.py
  backend/api/tests/test_views.py
  backend/api/urls.py
  backend/requirements.txt
Labels: app: be, pri: medium

#233 feat(backend): Dockerize the backend app
  backend/Dockerfile
  backend/docker-compose.yml
Labels: app: devops, pri: medium

#239 style(web): add design tokens and style configs
  .vscode/settings.json
  web/src/App.tsx
  web/src/index.css
  web/src/main.tsx
  web/src/theme.ts
Labels: app: fe, pri: high

#234 feat(web): create first login page
  .vscode/settings.json
  web/public/img/zenith-login-logo.webp
  web/src/App.tsx
  web/src/Login.tsx
  web/src/index.css
  web/src/main.tsx
  web/src/router.tsx
  web/tailwind.config.ts
Labels: app: fe, pri: medium

#242 feat(mobile): add login screen
  mobile/assets/Zenith.png
  mobile/assets/try.png
  mobile/assets/zenith-logo.svg
  mobile/components/CustomButton.tsx
  mobile/components/CustomInput.tsx
  mobile/screens/Login.tsx
Labels: pri: medium, app:mobile

#257 feat(web): add aria labels
  web/src/Login.tsx
Labels: app: fe, pri: medium

#259 feat(backend): inherit from AbstractBaseUser and add login and register API endpoints
  backend/api/serializer.py
  backend/api/tests/test_setup.py
  backend/api/tests/test_views.py
  backend/api/urls.py
  backend/api/views.py
  backend/config/settings.py
  backend/user/admin.py
  backend/user/migrations/0001_initial.py
  backend/user/migrations/0002_remove_user_is_active_remove_user_is_staff_and_more.py
  backend/user/migrations/0003_remove_user_groups_remove_user_is_superuser_and_more.py
  backend/user/models.py
Labels: type: improvement, app: be, pri: high

#260 feat(mobile): added navigation between home and login
  mobile/App.tsx
  mobile/assets/Zenith.png
  mobile/components/BottomTab.tsx
  mobile/components/CreatePostButton.tsx
  mobile/components/CustomButton.tsx
  mobile/components/CustomInput.tsx
  mobile/components/FeedHeader.tsx
  mobile/components/ProfileHeader.tsx
  mobile/components/SearchHeader.tsx
  mobile/components/Styles.tsx
  mobile/components/Types.tsx
  mobile/context/UserContext.tsx
  mobile/package-lock.json
  mobile/package.json
  mobile/screens/Feed.tsx
  mobile/screens/Home.tsx
  mobile/screens/Login.tsx
  mobile/screens/Profile.tsx
  mobile/screens/Search.tsx
  mobile/screens/Signup.tsx
Labels: type: improvement, pri: medium, app:mobile

#279 feat(backend): send proper respond status codes
  backend/api/tests/test_views.py
  backend/api/views.py
  backend/user/models.py
Labels: app: be, app: devops, pri: high

#267 feat(backend): add login and register functionality
  backend/.env.example
  backend/.gitignore
  backend/Dockerfile
  backend/README.md
  backend/api/__init__.py
  backend/api/serializer.py
  backend/api/tests/__init__.py
  backend/api/tests/test_setup.py
  backend/api/tests/test_views.py
  backend/api/urls.py
  backend/api/views.py
  backend/config/settings.py
  backend/config/urls.py
  backend/docker-compose.yml
  backend/requirements.txt
  backend/user/__init__.py
  backend/user/admin.py
  backend/user/apps.py
  backend/user/migrations/0001_initial.py
  backend/user/migrations/0002_remove_user_is_active_remove_user_is_staff_and_more.py
  backend/user/migrations/0003_remove_user_groups_remove_user_is_superuser_and_more.py
  backend/user/migrations/__init__.py
  backend/user/models.py
  backend/user/tests.py
  backend/user/views.py
  bruno/bruno.json
  bruno/environments/local.bru
  bruno/environments/test-env.bru
  bruno/how-to-use.md
  bruno/login.bru
  bruno/signup.bru
Labels: app: be, app: devops, pri: medium

#296 feat(devops): dockerize the whole application
  backend/Dockerfile
  backend/docker-compose.yml
  docker-compose.yml
  web/Dockerfile
  web/package-lock.json
  web/package.json
Labels: app: devops, pri: high

#298 Web/login register actions
  .vscode/settings.json
  bruno/environments/prod.bru
  bruno/login.bru
  bruno/signup.bru
  web/.env.example
  web/biome.json
  web/src/App.tsx
  web/src/Login.tsx
  web/src/Register.tsx
  web/src/Terms.tsx
  web/src/components/Button.tsx
  web/src/components/Checkmark.tsx
  web/src/index.css
  web/src/main.tsx
  web/src/router.tsx
  web/src/routes/Home.data.tsx
  web/src/routes/Home.tsx
  web/src/routes/Login.data.tsx
  web/src/routes/Login.tsx
  web/src/routes/Register.data.tsx
  web/src/routes/Register.tsx
  web/src/routes/Terms.tsx
  web/src/theme.ts
  web/tailwind.config.ts
Labels: app: fe, pri: high

#301 docs(web): update readme file
  web/README.md
Labels: app: fe

#300 feat(mobile): added async and storage methods
  mobile/components/CustomInput.tsx
  mobile/components/ProfileHeader.tsx
  mobile/components/SearchHeader.tsx
  mobile/components/StorageHandler.tsx
  mobile/components/Styles.tsx
  mobile/components/storageBullshit.tsx
  mobile/screens/Home.tsx
  mobile/screens/Login.tsx
  mobile/screens/Search.tsx
Labels: pri: high, app:mobile

#290 feat(web): implement actions and loaders for login and register
  .vscode/settings.json
  bruno/environments/prod.bru
  bruno/login.bru
  bruno/signup.bru
  web/.env.example
  web/README.md
  web/biome.json
  web/src/App.tsx
  web/src/Login.tsx
  web/src/Register.tsx
  web/src/Terms.tsx
  web/src/components/Button.tsx
  web/src/components/Checkmark.tsx
  web/src/index.css
  web/src/main.tsx
  web/src/router.tsx
  web/src/routes/Home.data.tsx
  web/src/routes/Home.tsx
  web/src/routes/Login.data.tsx
  web/src/routes/Login.tsx
  web/src/routes/Register.data.tsx
  web/src/routes/Register.tsx
  web/src/routes/Terms.tsx
  web/src/theme.ts
  web/tailwind.config.ts
Labels: app: fe, pri: medium

#293 feat(backend): add Swagger UI for login and signup API endpoints
  backend/api/urls.py
  backend/api/views.py
  backend/config/settings.py
  backend/requirements.txt
Labels: app: be, app: devops, pri: medium

#302 feat(backend): add `fullname` to the user model, update swagger and api tests
  backend/api/tests/test_setup.py
  backend/api/views.py
  backend/user/migrations/0004_user_fullname.py
  backend/user/models.py
Labels: app: be, pri: medium

#316 feat(web): add home page and search bar on header
  backend/docker-compose.yml
  bruno/environments/local.bru
  bruno/login.bru
  bruno/signup.bru
  web/.env.example
  web/.nvmrc
  web/package-lock.json
  web/package.json
  web/public/zenith-logo.png
  web/src/context/UserContext.tsx
  web/src/main.tsx
  web/src/router.tsx
  web/src/routes/Home.data.tsx
  web/src/routes/Home.tsx
  web/src/routes/Login.data.tsx
  web/src/routes/Login.tsx
  web/src/routes/Register.data.tsx
  web/src/routes/Register.tsx
  web/src/schema/user.ts
  web/src/theme.ts
Labels: app: fe, app: design, pri: high

#314 feat(mobile): implemented signup and login
  mobile/App.tsx
  mobile/README.md
  mobile/assets/Zenith.png
  mobile/assets/splash.png
  mobile/assets/try.png
  mobile/assets/zenith-logo-login.png
  mobile/components/BottomTab.tsx
  mobile/components/CreatePostButton.tsx
  mobile/components/CustomButton.tsx
  mobile/components/CustomInput.tsx
  mobile/components/FeedHeader.tsx
  mobile/components/ProfileHeader.tsx
  mobile/components/SearchHeader.tsx
  mobile/components/StorageHandler.tsx
  mobile/components/Styles.tsx
  mobile/components/Types.tsx
  mobile/context/ThemeContext.tsx
  mobile/context/UserContext.tsx
  mobile/package-lock.json
  mobile/package.json
  mobile/screens/Auth.tsx
  mobile/screens/Feed.tsx
  mobile/screens/Home.tsx
  mobile/screens/Login.tsx
  mobile/screens/Profile.tsx
  mobile/screens/Search.tsx
  mobile/screens/Signup.tsx
  mobile/tsconfig.json
Labels: app:mobile

#324 fix(backend): implement cors headers to allow requests from frontend
  backend/config/settings.py
  backend/docker-compose.yml
  backend/requirements.txt
  web/package-lock.json
Labels: type: bug, app: fe, app: be, pri: high

#326 feat(backend): implement Wikidata API and Swagger UI
  backend/api/tests/test_setup.py
  backend/api/urls.py
  backend/api/views.py
  backend/config/settings.py
  backend/requirements.txt
  backend/user/migrations/0004_user_fullname.py
  backend/user/models.py
Labels: app: be, pri: high, type: dependencies

#331 chore: milestone 2
  README.md
  backend/.env.example
  backend/README.md
  backend/api/tests/test_setup.py
  backend/api/urls.py
  backend/api/views.py
  backend/config/settings.py
  backend/requirements.txt
  backend/user/migrations/0004_user_fullname.py
  backend/user/models.py
  bruno/login.bru
  bruno/search.bru
  bruno/signup.bru
  mobile/App.tsx
  mobile/README.md
  mobile/assets/Zenith.png
  mobile/assets/splash.png
  mobile/assets/try.png
  mobile/assets/zenith-logo-login.png
  mobile/components/BottomTab.tsx
  mobile/components/CreatePostButton.tsx
  mobile/components/CustomButton.tsx
  mobile/components/CustomInput.tsx
  mobile/components/FeedHeader.tsx
  mobile/components/ProfileHeader.tsx
  mobile/components/SearchHeader.tsx
  mobile/components/StorageHandler.tsx
  mobile/components/Styles.tsx
  mobile/components/Types.tsx
  mobile/context/ThemeContext.tsx
  mobile/context/UserContext.tsx
  mobile/package-lock.json
  mobile/package.json
  mobile/screens/Auth.tsx
  mobile/screens/Feed.tsx
  mobile/screens/Home.tsx
  mobile/screens/Login.tsx
  mobile/screens/Profile.tsx
  mobile/screens/Search.tsx
  mobile/screens/Signup.tsx
  mobile/tsconfig.json
  web/.env.example
  web/package-lock.json
  web/src/routes/Login.data.tsx
  web/src/routes/Register.data.tsx
Labels: type: docs, app: fe, app: be, app: devops, pri: high, app:mobile

#329 feat(mobile): added search page to show results
  backend/api/urls.py
  backend/api/views.py
  backend/config/settings.py
  backend/requirements.txt
  mobile/components/InfoBox.tsx
  mobile/components/SearchHeader.tsx
  mobile/components/StorageHandler.tsx
  mobile/components/Styles.tsx
  mobile/screens/Home.tsx
  mobile/screens/Login.tsx
  mobile/screens/Search.tsx
  mobile/screens/Signup.tsx
Labels: pri: medium, app:mobile

#327 feat(web): complete milestone 2 work
  backend/api/views.py
  backend/config/settings.py
  backend/requirements.txt
  backend/user/migrations/0005_alter_user_email_alter_user_fullname_and_more.py
  bruno/environments/temp.bru
  bruno/login.bru
  web/.env.example
  web/.nvmrc
  web/package-lock.json
  web/package.json
  web/public/zenith-logo.png
  web/src/components/Button.tsx
  web/src/components/ImageLink.tsx
  web/src/components/InfoBox.tsx
  web/src/components/InlineLink.tsx
  web/src/context/UserContext.tsx
  web/src/index.css
  web/src/lib/storage.ts
  web/src/main.tsx
  web/src/router.tsx
  web/src/routes/Home.data.tsx
  web/src/routes/Home.tsx
  web/src/routes/Login.data.tsx
  web/src/routes/Login.tsx
  web/src/routes/Register.data.tsx
  web/src/routes/Register.tsx
  web/src/schema/search.ts
  web/src/schema/user.ts
  web/src/theme.ts
  web/vite.config.ts
Labels: app: fe

#334 feat(mobile): add search option and build configs
  .github/workflows/main.yml
  backend/api/views.py
  backend/requirements.txt
  mobile/app.json
  mobile/components/InfoBox.tsx
  mobile/components/SearchHeader.tsx
  mobile/components/StorageHandler.tsx
  mobile/components/Styles.tsx
  mobile/eas.json
  mobile/package-lock.json
  mobile/package.json
  mobile/screens/Home.tsx
  mobile/screens/Login.tsx
  mobile/screens/Search.tsx
  mobile/screens/Signup.tsx
Labels: pri: high, app:mobile

#337 Merge branch develop into main
  backend/api/views.py
  backend/config/settings.py
  backend/requirements.txt
  backend/user/migrations/0005_alter_user_email_alter_user_fullname_and_more.py
  bruno/environments/temp.bru
  bruno/login.bru
  mobile/app.json
  mobile/components/InfoBox.tsx
  mobile/components/SearchHeader.tsx
  mobile/components/StorageHandler.tsx
  mobile/components/Styles.tsx
  mobile/eas.json
  mobile/package-lock.json
  mobile/package.json
  mobile/screens/Home.tsx
  mobile/screens/Login.tsx
  mobile/screens/Search.tsx
  mobile/screens/Signup.tsx
  web/.env.example
  web/.nvmrc
  web/package-lock.json
  web/package.json
  web/public/zenith-logo.png
  web/src/components/Button.tsx
  web/src/components/ImageLink.tsx
  web/src/components/InfoBox.tsx
  web/src/components/InlineLink.tsx
  web/src/context/UserContext.tsx
  web/src/index.css
  web/src/lib/storage.ts
  web/src/main.tsx
  web/src/router.tsx
  web/src/routes/Home.data.tsx
  web/src/routes/Home.tsx
  web/src/routes/Login.data.tsx
  web/src/routes/Login.tsx
  web/src/routes/Register.data.tsx
  web/src/routes/Register.tsx
  web/src/schema/search.ts
  web/src/schema/user.ts
  web/src/theme.ts
  web/vite.config.ts
Labels: app: fe, app: devops, pri: high, app:mobile
