Repository bounswe/bounswe2024group11, pull requests merged in 2024-11, with the labels that each got.

#595 w3c(client): apply standards initiatives
  README.md
  client/src/components/forum-card.tsx
  client/src/components/logo.tsx
  package.json
  pnpm-lock.yaml
Labels: type: docs, pri: high, type: repo, type: research

#611 Lab6/backend/rate-quiz
  backend/core/admin.py
  backend/core/migrations/0011_takequiz.py
  backend/core/migrations/0012_rename_author_takequiz_quiz_taker.py
  backend/core/migrations/0013_rename_quiz_taker_takequiz_quiz_taker_user.py
  backend/core/migrations/0014_rename_takequiz_ratequiz_and_more.py
  backend/core/migrations/0015_rename_quiz_rater_user_ratequiz_user.py
  backend/core/migrations/0016_alter_ratequiz_unique_together.py
  backend/core/migrations/0017_alter_ratequiz_unique_together.py
  backend/core/migrations/0018_alter_ratequiz_unique_together.py
  backend/core/models.py
  backend/core/permissions.py
  backend/core/serializers.py
  backend/core/tests/test_rate_quiz.py
  backend/core/urls.py
  backend/core/views/rate_quiz_views.py
Labels: app: be

#624 feat(be): implement quiz and rate-quiz CRUD endpoints
  backend/config/settings.py
  backend/core/admin.py
  backend/core/fixtures/__init__.py
  backend/core/fixtures/data.json
  backend/core/migrations/0006_quiz_quizquestion.py
  backend/core/migrations/0007_rename_date_forumquestion_created_at_and_more.py
  backend/core/migrations/0008_rename_quiz_type_quiz_type.py
  backend/core/migrations/0009_rename_proficiency_level_quiz_difficulty.py
  backend/core/migrations/0010_rename_correct_answer_quizquestion_answer.py
  backend/core/migrations/0011_takequiz.py
  backend/core/migrations/0012_rename_author_takequiz_quiz_taker.py
  backend/core/migrations/0013_rename_quiz_taker_takequiz_quiz_taker_user.py
  backend/core/migrations/0014_rename_takequiz_ratequiz_and_more.py
  backend/core/migrations/0015_rename_quiz_rater_user_ratequiz_user.py
  backend/core/migrations/0016_alter_ratequiz_unique_together.py
  backend/core/migrations/0017_alter_ratequiz_unique_together.py
  backend/core/migrations/0018_alter_ratequiz_unique_together.py
  backend/core/models.py
  backend/core/permissions.py
  backend/core/serializers.py
  backend/core/tests/test_quiz.py
  backend/core/tests/test_rate_quiz.py
  backend/core/urls.py
  backend/core/views/forum_views.py
  backend/core/views/quiz_question_views.py
  backend/core/views/quiz_views.py
  backend/core/views/rate_quiz_views.py
Labels: app: be, pri: high

#629 feat(be): create an issue template for implementing model and modelviewset for django rest
  .github/ISSUE_TEMPLATE/modelviewset-issue.md
Labels: app: be, pri: low, type: repo

#630 repo(be): fix check-list for modelviewset issue tempate
  .github/ISSUE_TEMPLATE/modelviewset-issue.md
Labels: app: be, pri: low, type: repo

#634 feat(be): add new model QuizQuestionChoice to efficiently handle choice creation
  backend/core/migrations/0019_remove_quizquestion_answer_and_more.py
  backend/core/models.py
  backend/core/serializers.py
  backend/core/tests/test_quiz.py
  backend/core/tests/test_rate_quiz.py
Labels: type: improvement, app: be, pri: high

#641 feat(be): implement forum upvote and downvote endpoints and tests
  backend/core/migrations/0002_forumupvote.py
  backend/core/migrations/0003_forumdownvote.py
  backend/core/models.py
  backend/core/serializers/forum_vote_serializer.py
  backend/core/tests/test_forum_upvote_downvote.py
  backend/core/urls.py
  backend/core/views/forum_vote_views.py
Labels: app: be, pri: high

#642 feat(be): Implement Forum Answers
  backend/core/migrations/0004_forumanswer.py
  backend/core/migrations/0005_rename_date_forumanswer_created_at.py
  backend/core/models.py
  backend/core/serializers/serializers.py
  backend/core/tests/test_forum_answer.py
  backend/core/urls.py
  backend/core/views/forum_views.py
  backend/requirements.txt
Labels: app: be, pri: high

#645 feat(be) prepare at least 1 fixture for each model
  backend/core/fixtures/10_ratings.json
  backend/core/fixtures/1_users.json
  backend/core/fixtures/2_tags.json
  backend/core/fixtures/3_forum_questions.json
  backend/core/fixtures/4_forum_answers.json
  backend/core/fixtures/5_upvotes.json
  backend/core/fixtures/6_downvotes.json
  backend/core/fixtures/7_bookmarks.json
  backend/core/fixtures/8_quiz_1.json
  backend/core/fixtures/8_quiz_2.json
  backend/core/fixtures/9_takequizzes.json
  backend/core/fixtures/data.json
Labels: app: be, pri: high

#654 feat(mobile): add Leaderboard Screen
  mobile/app/screens/Leaderboard.tsx
  mobile/package-lock.json
  mobile/package.json
Labels: pri: medium, app:mobile

#669 feat(be): implement get translation endpoint
  backend/.env.example
  backend/core/urls.py
  backend/core/views/get_translation_views.py
Labels: app: be, pri: high

#671 feat(backend): implement hint mechanism for quiz question
  backend/core/urls.py
  backend/core/views/hint_views.py
Labels: app: be, pri: urgent

#667 feat(client): implement auth mechanism on actions to warn guests
  client/src/api.ts
  client/src/routes/Forum/Forum.data.tsx
  client/src/routes/Forum/Question.data.tsx
  client/src/routes/Home/Home.data.tsx
Labels: type: bug, type: improvement, app: fe

#676 feat(mobile): implement create answer mechanism
  mobile/app/components/VoteButtonsView.tsx
  mobile/app/screens/ForumQuestionDetail.tsx
  mobile/app/types/forum.ts
Labels: pri: medium, app:mobile

#659 feat(mobile): implement quiz screens
  backend/core/admin.py
  backend/core/fixtures/8_quiz_1.json
  backend/core/migrations/0008_alter_takequiz_unique_together_and_more.py
  backend/core/migrations/0009_remove_quizquestion_hint_text_and_more.py
  backend/core/models.py
  backend/core/serializers/serializers.py
  backend/core/serializers/take_quiz_serializer.py
  mobile/App.tsx
  mobile/android/app/src/main/AndroidManifest.xml
  mobile/app/components/QuizCard.tsx
  mobile/app/components/QuizCardBody.tsx
  mobile/app/components/QuizCardFooter.tsx
  mobile/app/components/QuizCardHeader.tsx
  mobile/app/components/QuizDetailText.tsx
  mobile/app/components/QuizQuestion.tsx
  mobile/app/components/QuizQuestionBody.tsx
  mobile/app/components/QuizQuestionButtons.tsx
  mobile/app/components/QuizQuestionHeader.tsx
  mobile/app/components/QuizQuestionOption.tsx
  mobile/app/components/QuizQuestionOptions.tsx
  mobile/app/components/TagCard.tsx
  mobile/app/components/TagCards.tsx
  mobile/app/components/ViewQuizButton.tsx
  mobile/app/context/AuthContext.tsx
  mobile/app/screens/CreateQuiz.tsx
  mobile/app/screens/Forum.tsx
  mobile/app/screens/Quiz.tsx
  mobile/app/screens/QuizDetail.tsx
  mobile/app/screens/QuizFeed.tsx
  mobile/app/screens/QuizResult.tsx
  mobile/app/screens/ViewQuiz.tsx
  mobile/app/types/forum.ts
  mobile/app/types/quiz.ts
  mobile/app/types/tag.ts
  mobile/db.json
  mobile/package-lock.json
  mobile/package.json
Labels: pri: medium, app:mobile

#692 Backend/quiz-difficulty
  backend/core/migrations/0008_quiz_quiz_point_quizquestion_question_point_and_more.py
  backend/core/models.py
  backend/core/serializers/serializers.py
  backend/core/urls.py
  backend/core/views/difficulty_views.py
  backend/requirements.txt
Labels: app: be, pri: high

#670 feat(mobile): implement vote and bookmark mechanism
  mobile/app/components/BookmarkButton.tsx
  mobile/app/components/ForumQuestionCard.tsx
  mobile/app/components/VoteButtonsView.tsx
  mobile/app/types/forum.ts
Labels: pri: medium, app:mobile

#696 feat(be): implement semantic search for quiz and forum question
  backend/core/urls.py
  backend/core/views/get_translation_views.py
  backend/core/views/helper.py
  backend/core/views/semantic_search_views.py
Labels: app: be, pri: high

#715 mobile(feat): implement quiz screens
  backend/core/views/get_translation_views.py
  backend/core/views/hint_views.py
  mobile/App.tsx
  mobile/app/components/BookmarkButton.tsx
  mobile/app/components/CreateQuizQuestionCore.tsx
  mobile/app/components/CreateQuizQuestionFooter.tsx
  mobile/app/components/CreateQuizQuestionHeader.tsx
  mobile/app/components/CreateQuizQuestionHints.tsx
  mobile/app/components/CreateQuizQuestionOptions.tsx
  mobile/app/components/CreateQuizQuestionSuggestionModal.tsx
  mobile/app/components/CreateQuizQuestionText.tsx
  mobile/app/components/DifficultyView.tsx
  mobile/app/components/NewQuizQuestion.tsx
  mobile/app/components/TranslationPicker.tsx
  mobile/app/components/VoteButtonsView.tsx
  mobile/app/context/AuthContext.tsx
  mobile/app/screens/CreateQuestion.tsx
  mobile/app/screens/CreateQuiz.tsx
  mobile/app/screens/CreateQuizQuestion.tsx
  mobile/app/screens/Forum.tsx
  mobile/app/screens/ForumQuestionDetail.tsx
  mobile/app/screens/QuizFeed.tsx
  mobile/app/screens/ReviewCreateQuiz.tsx
  mobile/app/screens/ViewQuiz.tsx
  mobile/app/types/quiz.ts
  mobile/ios/Podfile.lock
  mobile/package-lock.json
  mobile/package.json
Labels: pri: high, app:mobile

#717 feat(be): implement unittests for get_translation endpoint
  backend/core/tests/test_get_translation.py
Labels: type: improvement, app: be, pri: medium

#719 test(client): add tests for basic utility functions
  client/README.md
  client/package.json
  client/pnpm-lock.yaml
  client/src/ImageLink.tsx
  client/src/localstorage.ts
  client/src/main.tsx
  client/src/routes/Quiz/Quizzes.data.tsx
  client/src/tests/quiz.test.ts
  client/src/utils.tsx
Labels: app: fe
