Repository bounswe/bounswe2024group11, pull requests merged in 2024-05, with the labels that each got.

#354 refactor(api): change api structure for `login` and `signup` endpoints
  backend/api/serializer.py
  backend/api/urls.py
  backend/api/views.py
  backend/config/urls.py
  backend/user/serializer.py
  backend/user/urls.py
  backend/user/views.py
  bruno/login.bru
  bruno/search.bru
  bruno/signup.bru
  bruno/swagger.bru
Labels: app: be, pri: medium

#355 feat(mobile): added create post screen
  mobile/app.json
  mobile/components/CreatePostButton.tsx
  mobile/components/CustomInput.tsx
  mobile/components/Post.tsx
  mobile/components/SearchHeader.tsx
  mobile/components/StorageHandler.tsx
  mobile/components/Styles.tsx
  mobile/components/Types.tsx
  mobile/screens/CreatePost.tsx
  mobile/screens/Feed.tsx
  mobile/screens/Home.tsx
  mobile/screens/Login.tsx
  mobile/screens/Post.tsx
  mobile/screens/Search.tsx
  mobile/screens/Signup.tsx
Labels: app:mobile

#360 feat(mobile): added post component
  mobile/components/Post.tsx
  mobile/components/Styles.tsx
  mobile/package-lock.json
  mobile/screens/CreatePost.tsx
  mobile/screens/Feed.tsx
Labels: pri: high, app:mobile

#361 [wip] feat(backend): create wikidata-suggestions endpoint and post-search endpoint
  backend/user/queries.py
  backend/user/urls.py
  backend/user/views.py
  backend/user/wikidata_methods.py
  bruno/create post.bru
  bruno/search for posts.bru
  bruno/search.bru
  bruno/wikidata suggestion.bru
Labels: app: be, pri: high

#363 [wip] feat: add new implementation for wikidata and search endpoints
  .github/workflows/main.yml
  README.md
  backend/api/serializer.py
  backend/api/urls.py
  backend/api/views.py
  backend/config/urls.py
  backend/requirements.txt
  backend/user/queries.py
  backend/user/serializer.py
  backend/user/urls.py
  backend/user/views.py
  backend/user/wikidata_methods.py
  bruno/create post.bru
  bruno/login.bru
  bruno/search posts.bru
  bruno/search.bru
  bruno/signup.bru
  bruno/swagger.bru
  bruno/wikidata suggestion.bru
Labels: app: be, pri: medium

#356 feat(backend): Added test_token endpoint
  backend/user/urls.py
  backend/user/views.py
  bruno/token test.bru
Labels: app: be, pri: high

#362 feat(devops): added nginx conf file under nginx directory and modified docker-compose.yml.
  docker-compose.yml
  nginx/nginx.conf
Labels: app: devops, pri: medium

#366 hotfix(backend): HTTP request method change
  backend/.env.example
  backend/config/settings.py
  backend/user/urls.py
  backend/user/views.py
  backend/user/wikidata_methods.py
  bruno/login.bru
  bruno/search posts.bru
  bruno/signup.bru
  bruno/token test.bru
  bruno/wikidata suggestion.bru
  docker-compose.yml
  nginx/nginx.conf
Labels: app: be, pri: urgent

#371 feat(mobile): added suggestion feature in the search bars in the app
  mobile/components/SearchHeader.tsx
  mobile/components/StorageHandler.tsx
  mobile/components/Styles.tsx
  mobile/screens/CreatePost.tsx
  mobile/screens/Search.tsx
Labels: pri: medium, app:mobile

#368 fix: divided request by methods and added error
  .github/workflows/main.yml
  README.md
  backend/api/serializer.py
  backend/api/urls.py
  backend/api/views.py
  backend/config/settings.py
  backend/config/urls.py
  backend/requirements.txt
  backend/user/queries.py
  backend/user/serializer.py
  backend/user/urls.py
  backend/user/views.py
  backend/user/wikidata_methods.py
  bruno/create post.bru
  bruno/login.bru
  bruno/search posts.bru
  bruno/search.bru
  bruno/signup.bru
  bruno/swagger.bru
  bruno/wikidata suggestion.bru
  mobile/components/SearchHeader.tsx
  mobile/components/StorageHandler.tsx
  mobile/components/Styles.tsx
  mobile/screens/CreatePost.tsx
  mobile/screens/Home.tsx
  mobile/screens/Login.tsx
  mobile/screens/Search.tsx
  mobile/screens/Signup.tsx
Labels: type: improvement, app:mobile

#373 feat(mobile): Post Screen and Navigation added
  mobile/components/Post.tsx
  mobile/components/Styles.tsx
  mobile/components/Types.tsx
  mobile/package-lock.json
  mobile/screens/Feed.tsx
  mobile/screens/Home.tsx
  mobile/screens/Post.tsx
Labels: pri: high, app:mobile

#379 feat(mobile): added token to user context and api calls
  mobile/components/ProfileHeader.tsx
  mobile/components/ProfileInfo.tsx
  mobile/components/StorageHandler.tsx
  mobile/components/Styles.tsx
  mobile/context/UserContext.tsx
  mobile/screens/CreatePost.tsx
  mobile/screens/Home.tsx
  mobile/screens/Login.tsx
  mobile/screens/Post.tsx
  mobile/screens/Profile.tsx
  mobile/screens/Signup.tsx
Labels: pri: high, app:mobile

#385 feat(backend): add like and bookmark counters, user_id, liked_by_list to post
  backend2/core/models.py
  backend2/core/serializers.py
  backend2/core/urls.py
  backend2/core/views.py
  bruno/search posts.bru
Labels: app: be, pri: high

#382 feat(backend): add swagger ui
  backend2/config/settings.py
  backend2/core/urls.py
  backend2/core/views.py
  backend2/swagger_docs/__init__.py
  backend2/swagger_docs/wikidata_swagger.py
Labels: type: docs, app: be, pri: medium

#387 fix(backend): add authorization rules and unique constraints for like, bookmark and follow endpoints
  backend2/core/migrations/0002_alter_bookmark_unique_together_and_more.py
  backend2/core/models.py
  backend2/core/permissions.py
  backend2/core/serializers.py
  backend2/core/urls.py
  backend2/core/views.py
  bruno/search posts.bru
Labels: type: improvement, app: be, pri: high

#391 feat: added edit post
  mobile/components/EditPostButton.tsx
  mobile/components/Types.tsx
  mobile/screens/EditPost.tsx
  mobile/screens/Feed.tsx
  mobile/screens/Home.tsx
Labels: pri: high, app:mobile

#392 feat(mobile): added http requests to the post screen
  mobile/components/CreatePostButton.tsx
  mobile/components/EditPostButton.tsx
  mobile/components/FeedHeader.tsx
  mobile/components/Post.tsx
  mobile/components/ProfileHeader.tsx
  mobile/components/ProfileInfo.tsx
  mobile/components/StorageHandler.tsx
  mobile/components/Types.tsx
  mobile/screens/CreatePost.tsx
  mobile/screens/Feed.tsx
  mobile/screens/Home.tsx
  mobile/screens/Login.tsx
  mobile/screens/Post.tsx
  mobile/screens/Profile.tsx
  mobile/screens/Profiles.tsx
  mobile/screens/Search.tsx
  mobile/screens/Signup.tsx
Labels: pri: high, app:mobile

#381 fix(backend): Add check for deleting posts, update is working fine with PATCH.
  backend2/core/views.py
Labels: type: bug, app: be, pri: medium

#369 feature(web): implement create post, view post, and post edit delete dropdown ui
  mobile/screens/Auth.tsx
  mobile/screens/Home.tsx
  web/biome.json
  web/public/add-fill.svg
  web/src/components/Button.tsx
  web/src/components/Checkmark.tsx
  web/src/components/NewPost.tsx
  web/src/components/Post.tsx
  web/src/context/UserContext.tsx
  web/src/index.css
  web/src/main.tsx
  web/src/router.tsx
  web/src/routes/Home.data.ts
  web/src/routes/Home.tsx
  web/src/routes/Login.data.ts
  web/src/routes/Login.tsx
  web/src/routes/Profile.data.ts
  web/src/routes/Profile.data.tsx
  web/src/routes/Profile.tsx
  web/src/routes/Register.data.ts
  web/src/routes/global/auth.data.ts
  web/src/routes/shadow/Suggestions.data.ts
  web/src/routes/shadow/post/Bookmark.data.ts
  web/src/routes/shadow/post/Like.data.ts
  web/src/routes/shadow/profile/DeleteProfile.data.ts
  web/src/routes/shadow/profile/Follow.data.ts
  web/src/routes/shadow/profile/UpdateBio.data.ts
  web/src/routes/shadow/profile/UpdateProfile.data.ts
  web/src/schema/user.ts
  web/src/theme.ts
  web/src/utils/date.ts
  web/src/utils/form.ts
Labels: type: improvement, app: fe, app: design, pri: medium, type: dependencies, type: help wanted

#389 feat(backend): add profile endpoint
  backend2/core/admin.py
  backend2/core/migrations/0002_profile.py
  backend2/core/models.py
  backend2/core/permissions.py
  backend2/core/serializers.py
  backend2/core/urls.py
  backend2/core/views.py
Labels: app: be, pri: urgent

#413 feat(backend): merge backend v2
  backend2/.env.example
  backend2/.gitignore
  backend2/Dockerfile
  backend2/config/__init__.py
  backend2/config/asgi.py
  backend2/config/settings.py
  backend2/config/urls.py
  backend2/config/wsgi.py
  backend2/core/__init__.py
  backend2/core/admin.py
  backend2/core/apps.py
  backend2/core/migrations/0001_initial.py
  backend2/core/migrations/0002_alter_bookmark_unique_together_and_more.py
  backend2/core/migrations/0002_profile.py
  backend2/core/migrations/0003_merge_20240516_1526.py
  backend2/core/migrations/0004_rename_profile_owner_profile_owner_and_more.py
  backend2/core/migrations/__init__.py
  backend2/core/models.py
  backend2/core/permissions.py
  backend2/core/queries.py
  backend2/core/serializers.py
  backend2/core/tests/__init__.py
  backend2/core/tests/test_login.py
  backend2/core/urls.py
  backend2/core/views.py
  backend2/core/wikidata_helpers.py
  backend2/manage.py
  backend2/requirements.txt
  backend2/swagger_docs/__init__.py
  backend2/swagger_docs/swagger.py
  bruno/follow.bru
  bruno/login.bru
  bruno/search posts.bru
  bruno/signup.bru
  bruno/unfollow.bru
  docker-compose.yml
Labels: app: be, pri: urgent

#425 Merge develop-backend into develop
  backend/README.md
  backend/api/tests/__init__.py
  backend/api/tests/test_setup.py
  backend/api/tests/test_views.py
  backend/api/urls.py
  backend/api/views.py
  backend/config/settings.py
  backend/config/urls.py
  backend/core/__init__.py
  backend/core/admin.py
  backend/core/apps.py
  backend/core/migrations/0001_initial.py
  backend/core/migrations/0002_alter_bookmark_unique_together_and_more.py
  backend/core/migrations/0002_profile.py
  backend/core/migrations/0003_merge_20240516_1526.py
  backend/core/migrations/0004_rename_profile_owner_profile_owner_and_more.py
  backend/core/migrations/__init__.py
  backend/core/models.py
  backend/core/permissions.py
  backend/core/queries.py
  backend/core/serializers.py
  backend/core/tests/__init__.py
  backend/core/tests/test_login.py
  backend/core/urls.py
  backend/core/views.py
  backend/core/wikidata_helpers.py
  backend/requirements.txt
  backend/swagger_docs/__init__.py
  backend/swagger_docs/swagger.py
  backend/user/admin.py
  backend/user/migrations/0001_initial.py
  backend/user/migrations/0002_remove_user_is_active_remove_user_is_staff_and_more.py
  backend/user/migrations/0003_remove_user_groups_remove_user_is_superuser_and_more.py
  backend/user/migrations/0004_user_fullname.py
  backend/user/migrations/0005_alter_user_email_alter_user_fullname_and_more.py
  backend/user/migrations/__init__.py
  backend/user/models.py
  backend/user/serializer.py
  backend/user/tests.py
  backend/user/urls.py
  backend/user/views.py
  backend/user/wikidata_methods.py
  backend/zenith/admin.py
  backend/zenith/apps.py
  backend/zenith/migrations/__init__.py
  backend/zenith/models.py
  backend/zenith/tests.py
  backend/zenith/views.py
  bruno/follow.bru
  bruno/login.bru
  bruno/search posts.bru
  bruno/signup.bru
  bruno/unfollow.bru
Labels: app: be

#426 feat(backend): expose wiki data info endpoint
  backend/core/queries.py
  backend/core/tests/test_info.py
  backend/core/urls.py
  backend/core/views.py
  backend/core/wikidata_helpers.py
  backend/swagger_docs/swagger.py
Labels: type: improvement, app: be, pri: high

#431 feat(mobile): connect to backend
  mobile/components/Post.tsx
  mobile/components/StorageHandler.tsx
  mobile/context/UserContext.tsx
  mobile/screens/CreatePost.tsx
  mobile/screens/Feed.tsx
  mobile/screens/Login.tsx
  mobile/screens/Post.tsx
  mobile/screens/Search.tsx
  mobile/screens/Signup.tsx
Labels: pri: urgent, app:mobile

#430 fix(backend): add fullname field to user serializers
  backend/core/serializers.py
  bruno/get users.bru
  bruno/login.bru
  bruno/signup.bru
Labels: app: be, pri: urgent

#441 feat(backend): add unique profiles for each user
  backend/core/migrations/0005_alter_profile_owner.py
  backend/core/models.py
  backend/core/serializers.py
  backend/core/views.py
Labels: app: be, pri: high

#423 feat(mobile) : add EditProfile screen and created mute,block,follow buttons
  mobile/components/InfoBox.tsx
  mobile/components/ProfileInfo.tsx
  mobile/components/StorageHandler.tsx
  mobile/components/Types.tsx
  mobile/package-lock.json
  mobile/screens/EditPost.tsx
  mobile/screens/EditProfile.tsx
  mobile/screens/Home.tsx
  mobile/screens/Login.tsx
  mobile/screens/Post.tsx
Labels: pri: high, app:mobile

#444 feat(web): add schema validation for login and register, and add error message handling
  web/package-lock.json
  web/package.json
  web/src/routes/Bookmarks.data.ts
  web/src/routes/Home.data.ts
  web/src/routes/Login.data.ts
  web/src/routes/Login.tsx
  web/src/routes/Profile.data.ts
  web/src/routes/Register.data.ts
  web/src/routes/Register.tsx
  web/src/routes/global/auth.data.ts
  web/src/types/search.ts
  web/src/types/user.ts
Labels: app: fe, pri: high

#448 fix(mobile): handled response types and component renderings
  mobile/components/InfoBox.tsx
  mobile/components/Post.tsx
  mobile/components/ProfileInfo.tsx
  mobile/components/StorageHandler.tsx
  mobile/components/Styles.tsx
  mobile/components/Types.tsx
  mobile/screens/CreatePost.tsx
  mobile/screens/EditPost.tsx
  mobile/screens/EditProfile.tsx
  mobile/screens/Feed.tsx
  mobile/screens/Home.tsx
  mobile/screens/Post.tsx
  mobile/screens/Profile.tsx
  mobile/screens/Search.tsx
Labels: type: bug, pri: urgent, app:mobile

#450 feat(backend): update profile endpoint's returns, delete follow by gi…
  backend/core/models.py
  backend/core/serializers.py
  backend/core/views.py
Labels: app: be, pri: high

#446 feat(backend): Update profile functionalities, follow functionalities, user fullname fields. Add tests
  backend/core/migrations/0001_initial.py
  backend/core/models.py
  backend/core/queries.py
  backend/core/serializers.py
  backend/core/tests/test_info.py
  backend/core/tests/test_search.py
  backend/core/tests/test_suggestions.py
  backend/core/urls.py
  backend/core/views.py
  backend/core/wikidata_helpers.py
  backend/swagger_docs/swagger.py
  bruno/bruno.json
  bruno/environments/prod.bru
  bruno/environments/temp.bru
  bruno/environments/test-env.bru
  bruno/follow.bru
  bruno/how-to-use.md
  bruno/swagger.bru
  bruno/token test.bru
  bruno/unfollow.bru
  bruno/wikidata suggestion.bru
Labels: app: be, pri: high
